export const DATA_FETCH_SUCCESS = "DATA_FETCH_SUCCESS";
export const DATA_FETCH_FAILED = "DATA_FETCH_FAILED";
export const DETAILS_FETCH_SUCCESS = "DETAILS_FETCH_SUCCESS";
export const DETAILS_FETCH_FAILED = "DETAILS_FETCH_FAILED";
export const PRODUCT_CREATE = "PRODUCT_CREATE";
export const PRODUCT_UPDATE = "PRODUCT_UPDATE";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
